//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSepetiProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class TBLKategoriler
    {
        public TBLKategoriler()
        {
            this.TBLYemekler = new HashSet<TBLYemekler>();
        }

        public short KategoriId { get; set; }

        [Required(ErrorMessage = "Bu alan boþ geçilemez")]
        public string KategoriAdi { get; set; }

        public virtual ICollection<TBLYemekler> TBLYemekler { get; set; }
    }
}
