//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace YemekSepetiProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLKullanicilar
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Kullanýcý adý boþ geçilemez")]
        public string KullaniciAdi { get; set; }
        [Required(ErrorMessage = "Þifre boþ geçilemez")]
        public string Sifre { get; set; }
        public string Rol { get; set; }
    }
}
