//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace YemekSepetiProjesi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class TBLMusteriler
    {
        public TBLMusteriler()
        {
            this.TBLSatislar = new HashSet<TBLSatislar>();
        }

        public int MusteriId { get; set; }
        [Required(ErrorMessage = "Bu alan boþ geçilemez")]
        [StringLength(50, ErrorMessage = "Girilen deðer 50 karakteri geçemez.")]
        public string MusteriAdi { get; set; }
        [Required(ErrorMessage = "Bu alan boþ geçilemez")]
        [StringLength(50, ErrorMessage = "Girilen deðer 50 karakteri geçemez.")]
        public string MusteriSoyad { get; set; }

        public virtual ICollection<TBLSatislar> TBLSatislar { get; set; }
    }
}
